<a href="https://colab.research.google.com/github/Leegyu66/Numpy-master/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.21.6'

## 리스트로 배열 만들기

In [3]:
a1 = np.array([1, 2, 3, 4, 5]) # 1차원 배열 생성
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [4]:
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]) # 2차원 배열 생성
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [5]:
a3 = np.array([[ [1, 2, 3], [4, 5, 6], [7, 8, 9] ], # 3차원 배열 생성성
              [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
              [ [1, 2, 3], [4, 5, 6], [7, 8, 9 ]]])

print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


## 배열 생성 및 초기화

- zeros(): 모든 요소를 0으로 초기화

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones(): 모든 요소를 1로 초기화

In [7]:
np.ones(10)
np.ones((3, 3)) # 2차원도 가능

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full():모든 요소를 지정한 값으로 초기화

In [8]:
np.full((3, 3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

- eye(): 단위행렬(identity matrix) 생성
  - 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- tri(): 삼각행렬 생성

In [10]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

- empty(): 초기화되지 않은 배열 생성

In [11]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- _like(): 지정된 배열과 shape가 같은 행렬 생성

In [12]:
print(a1)
np.zeros_like(a1) # a1의 shape과 같은 모양으로 0이 채워진 배열을 만들어달라

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [13]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

## 생성한 값으로 배열 생성성

- arange(): 정수 범위로 배열 생성

In [15]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- linspace(): 범위 내에서 균등 간격의 배열 생성

In [16]:
np.linspace(0, 1, 5) # 0부터 1까지 균등한 간격으로 5개의 원소를 가진 배열을 생성해달라라

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- longspace(): 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [17]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

## 랜덤값으로 배열 생성

- random.random(): 랜덤한 수의 배열 생성

In [18]:
np.random.random((3, 3))

array([[0.27047775, 0.61341892, 0.82355732],
       [0.90112178, 0.78329465, 0.23060339],
       [0.37078472, 0.06738209, 0.44799529]])

- random.randint(): 일정 구간의 랜덤 정수의 배열 생성

In [19]:
np.random.randint(0, 10, (3, 3))

array([[6, 5, 4],
       [7, 2, 4],
       [8, 6, 9]])

- random.normal(): 정규분포를 고려한 랜덤한 수의 배열 생성

In [20]:
np.random.normal(0, 1, size=(3, 3))

array([[ 1.42558306,  0.66597032, -0.143239  ],
       [ 1.32759861,  0.68053314,  0.46354518],
       [ 1.14595854, -1.50160881, -0.78520489]])

random.rand(): 균등분포를 고려한 랜덤한 수의 배열 생성

In [21]:
np.random.rand(3, 3)


array([[0.34719052, 0.00853223, 0.76205565],
       [0.71587478, 0.50988533, 0.67541758],
       [0.52753312, 0.13578166, 0.10420135]])

- random.randn(): 표준 정규 분포를 고려한 랜덤한 수의 배열 생성

In [22]:
np.random.randn(3, 3)

array([[ 0.01846199,  0.20417086,  0.11149089],
       [ 1.08251584, -0.99345567,  0.78679452],
       [-0.10709013, -0.59145925, -1.18797258]])

## 표준 데이터 타입

In [23]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 날짜/시간 배열 생성

In [26]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [27]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [28]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [29]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

## 배열 조회

## 배열 속성 정보

In [30]:
def array_info(array):
  print(array)
  print('ndim:', array.ndim)
  print("shape:", array.shape)
  print("dtype:", array.dtype)
  print('size:', array.size)
  print('itemsize:', array.itemsize)
  print('nbytes:', array.nbytes)
  print('strides:', array.strides)

In [31]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [32]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [33]:
array_info(a3) # 한 차원을 넘어갈 때 필요한 크기(strides)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


## 인덱싱

In [34]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [35]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [36]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[2, -1, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


## 슬라이싱

- 슬라이싱 구문: a[start:stop:step]
- 기본값: start=0, stop=ndim, step=1

In [37]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [38]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1]) # 1부터 끝까지([4 5 6][7 8 9])의 전체를 -1스텝으로 출력
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 불리언 인덱싱
- 배열 각 요소의 선택 여부를 불리언으로 지정
- True 값인 인덱스의 값만 조회

In [39]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi]) # True의 위치인 값만 출력
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [40]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True  True]
 [False  True False]
 [ True  True  True]]
[1 2 3 5 7 8 9]


## 팬시 인덱싱

In [41]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])
ind = np.array([[0, 1],
                [2, 0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [42]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


## 배열 값 삽입

- insert(): 배열의 특정 위치에 값 삽입
- axis를 지정하지 않으면 1차원 배열로 변환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [43]:
print(a1)
b1 = np.insert(a1, 0, 10) # a1 0번째 위치에 10삽입 휘발성?
print(b1)
print(a1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [44]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0) # axis로 축을 지정 axis가 0이면 행 1이면 열
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


## 배열 값 수정
  - 인덱싱

In [45]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 5 6 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [46]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)
a2[1:, 2] = 9
print(a2)
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


## 배열 값 삭제
- delete(): 배열의 특정 위치에 값 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [47]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [48]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


## 배열 복사
   - 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [49]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2] # 슬라이싱을 원본배열을 카피하여서 주는것이 아닌 메모리를 그대로 쓰는것임
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


- copy(): 배열이나 하위 배열 내의 값을 명시적으로 복사

In [50]:
print(a2)
a2_sub_copy = a2[:2, :2].copy() # 원본을 유지하고 싶으면 .copy()를 써야한다
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


## 배열 변환

### 배열 전치 및 축 변경

In [51]:
print(a2)
print(a2.T) # 행, 열 뒤집힘힘

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [52]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [53]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [54]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


- reshape(): 배열의 형상을 변경

In [57]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- newaxis(): 새로운 축 추가

In [59]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


## 배열 크기 변경

- 배열 모양만 변경

In [76]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[7 1 2 2 9]
 [9 8 7 0 0]]
[[7 1]
 [2 2]
 [9 9]
 [8 7]
 [0 0]]


- 배열 크기 증가
- 남은 공간은 0으로 채워짐

In [78]:
n2.resize((5, 5), refcheck=False)
print(n2)

[[7 1 2 2 9]
 [9 8 7 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열 크기 감소
- 포함되지 않은 값은 누락됨

In [79]:
n2.resize((3, 3), refcheck=False)
print(n2)

[[7 1 2]
 [2 9 9]
 [8 7 0]]


## 배열 추가
- append(): 배열의 끝에 값 추가

In [80]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


- axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [86]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 배열 연결결

- concatenate(): 튜플이나 배열의 리스트를 인수로 사용해 배열 연결 

In [88]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [90]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [92]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [93]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- vstack(): 수직 스택(vertical stack), 1차원으로 연결

In [94]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- hstack(): 수평 스택(horizontal stack), 2차원으로 연결

In [95]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack(): 깊이 스택(depth stack), 3차원으로 연결

In [96]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- stack(): 새로운 차원으로 연결

In [103]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

## 배열 분할

- split(): 배열 분할할

In [109]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1,[2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


- vsplit(): 수직 분할, 1차원으로 분할

In [110]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


- hsplit(): 수평 분할, 2차원으로 분할

In [113]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


- dsplit(): 깊이 분할, 3차원으로 분할

In [115]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


## 배열 연산

- NumPy의 배열 연산은 벡터화(vectorized)연산을 사용
- 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
- 배열 요소에 대한 반복적인 계산을 효율적으로 수행

## 브로드캐스팅(Broadcasting)

In [118]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a2 + a1)

b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1+b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 산술 연산(Arithmetic Operators)

In [129]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.subtract(a1, 10))

print(-a1)
print(np.negative(a1))

print(a1 * 2)
print(np.multiply(a1, 2))

print(a1 / 2)
print(np.divide(a1, 2))

print(a1 // 2)
print(np.floor_divide(a1, 2))

print(a1 ** 2)
print(np.power(a1, 2))

print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [131]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[9 1 9 3 5 3 2 6 2]
[10  3 12  7 10  9  9 14 11]
[-8  1 -6  1  0  3  5  2  7]
[0.11111111 2.         0.33333333 1.33333333 1.         2.
 3.5        1.33333333 4.5       ]
[0 2 0 1 1 2 3 1 4]
[     1      2  19683     64   3125    216     49 262144     81]
[1 0 3 1 0 0 1 2 1]


In [134]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.random.randint(1, 10, size=(3, 3))
print(b2)

print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 9 5]
 [1 5 5]
 [7 3 9]]
[[ 5 11  8]
 [ 5 10 11]
 [14 11 18]]
[[-3 -7 -2]
 [ 3  0  1]
 [ 0  5  0]]
[[ 4 18 15]
 [ 4 25 30]
 [49 24 81]]
[[0.25       0.22222222 0.6       ]
 [4.         1.         1.2       ]
 [1.         2.66666667 1.        ]]
[[0 0 0]
 [4 1 1]
 [1 2 1]]
[[        1       512       243]
 [        4      3125      7776]
 [   823543       512 387420489]]
[[1 2 3]
 [0 0 1]
 [0 2 0]]


## 절대값 함수(Absolute Function)
- absolute(), abs(): 내장된 절대값 함수

In [135]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(np.absolute(a1))

[ -2  -1 -10  -7  -8]
[ 2  1 10  7  8]


## 제곱/제곱근 함수
- square(), sqrt(): 제곱, 제곱근 함수

In [136]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ -2  -1 -10  -7  -8]
[  4   1 100  49  64]
[nan nan nan nan nan]


<ipython-input-136-4e034cb7ea92>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


## 지수와 로그 함수 (Exponential and Log Function)

In [137]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[5 1 6 6 9]
[1.48413159e+02 2.71828183e+00 4.03428793e+02 4.03428793e+02
 8.10308393e+03]
[ 32.   2.  64.  64. 512.]
[25  1 36 36 81]


In [138]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[5 1 6 6 9]
[1.60943791 0.         1.79175947 1.79175947 2.19722458]
[2.32192809 0.         2.5849625  2.5849625  3.169925  ]
[0.69897    0.         0.77815125 0.77815125 0.95424251]


## 삼각함수

In [139]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [140]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


## 집계 함수

In [141]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
49 49
[17 18 14] [17 18 14]
[21  9 19] [21  9 19]


In [143]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
[ 8 13 21 22 27 30 38 46 49]
[[ 8  5  8]
 [ 9 10 11]
 [17 18 14]]
[[ 8 13 21]
 [ 1  6  9]
 [ 8 16 19]]


In [144]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
[[-3  3]
 [ 4 -2]
 [ 0 -5]]
[[-7  0 -5]
 [ 7  3  0]]
[[-3  3]
 [ 4 -2]
 [ 0 -5]]


In [146]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
921600
[ 64 200  72]
[320  15 192]


In [147]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[21 21 21]
 [ 9  9  9]
 [19 19 19]]
[[21 21 21]
 [ 9  9  9]
 [19 19 19]]


In [148]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
49
[[[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]]
[[21 21 21]
 [ 9  9  9]
 [19 19 19]]


In [150]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


In [151]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[21 21 21]
 [ 9  9  9]
 [19 19 19]]
[[8 8 8 8 8 8 8 8 8]
 [5 5 5 5 5 5 5 5 5]
 [8 8 8 8 8 8 8 8 8]
 [1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5]
 [3 3 3 3 3 3 3 3 3]
 [8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8]
 [3 3 3 3 3 3 3 3 3]]


In [152]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
5.444444444444445
[5.66666667 6.         4.66666667]
[7.         3.         6.33333333]


In [153]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
2.543449587168799
[3.29983165 1.41421356 2.3570226 ]
[1.41421356 1.63299316 2.3570226 ]


In [154]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
6.469135802469136
[10.88888889  2.          5.55555556]
[2.         2.66666667 5.55555556]


In [155]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
1
[1 5 3]
[5 1 3]


In [156]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
8
[8 8 8]
[8 5 8]


In [157]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
3
[1 0 1]
[1 0 2]


In [158]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
0
[0 2 0]
[0 1 0]


In [159]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[8 5 8]
 [1 5 3]
 [8 8 3]]
5.0
[8. 5. 3.]
[8. 3. 8.]


In [161]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [162]:
a2 = np.array([[False, False, False], 
               [False, True, True],
               [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


In [164]:
a2 = np.array([[False, False, True], 
               [True, True, True],
               [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


## 비교 연산

In [168]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print (a1 < 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[False False False False  True  True  True  True  True]


In [169]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]


TypeError: ignored

In [171]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]


## 불리언 연산자

In [172]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5)] & (a2 < 8))

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5)] | (a2 < 8))

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5)] ^ (a2 < 8))

print(~(a2 > 5))
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


## 배열 정렬

In [175]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[9 7 6 3 3 5 4 4 8 8]
[3 3 4 4 5 6 7 8 8 9]
[9 7 6 3 3 5 4 4 8 8]
[3 4 6 7 5 2 1 8 9 0]
[9 7 6 3 3 5 4 4 8 8]
None
[3 3 4 4 5 6 7 8 8 9]


In [177]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[1 6 2]
 [9 1 8]
 [8 7 1]]
[[1 1 1]
 [8 6 2]
 [9 7 8]]
[[1 2 6]
 [1 8 9]
 [1 7 8]]


## 부분 정렬
- partition(): 배열에서 k개의 작은 값을 반환

In [178]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3)) # 제일 작은 값 3개개

[9 2 4 8 6 7 4 6 7 3]
[3 2 4 4 6 6 7 8 7 9]


In [180]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[1 2 3 8 1]
 [5 2 6 3 2]
 [9 7 9 5 2]
 [8 4 6 8 9]
 [9 3 3 6 6]]
[[1 1 2 3 8]
 [3 2 2 5 6]
 [5 2 7 9 9]
 [4 6 8 8 9]
 [3 3 6 6 9]]
[[8 2 3 3 1]
 [1 2 3 5 2]
 [5 3 6 6 2]
 [9 4 6 8 6]
 [9 7 9 8 9]]
[[1 1 2 3 8]
 [3 2 2 5 6]
 [5 2 7 9 9]
 [4 6 8 8 9]
 [3 3 6 6 9]]


## 배열 입출력

In [182]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save("a", a2)

[[1 7 8 9 5]
 [9 2 2 4 8]
 [5 7 8 2 1]
 [9 6 8 8 6]
 [3 6 7 9 2]]


In [186]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab", a2, b2) # z를 붙이면 여러 배열을 한 번에 묶을 수 있다다

[[9 4 2 5 5]
 [9 6 5 7 4]
 [5 5 3 5 7]
 [1 7 3 4 6]
 [4 3 3 9 3]]


In [188]:
!ls

ab.npz	a.npy  sample_data


In [189]:
npy = np.load("a.npy")
print(npy)

[[1 7 8 9 5]
 [9 2 2 4 8]
 [5 7 8 2 1]
 [9 6 8 8 6]
 [3 6 7 9 2]]


In [193]:
npz = np.load("ab.npz")
print(npz)
print(npz.files)
print(npz["arr_0"], '\n\n', npz["arr_1"])

['arr_0', 'arr_1']
[[1 7 8 9 5]
 [9 2 2 4 8]
 [5 7 8 2 1]
 [9 6 8 8 6]
 [3 6 7 9 2]] 

 [[9 4 2 5 5]
 [9 6 5 7 4]
 [5 5 3 5 7]
 [1 7 3 4 6]
 [4 3 3 9 3]]


In [194]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',')

[[1 7 8 9 5]
 [9 2 2 4 8]
 [5 7 8 2 1]
 [9 6 8 8 6]
 [3 6 7 9 2]]


In [195]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [198]:
!cat a.csv

1.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00,5.000000000000000000e+00
9.000000000000000000e+00,2.000000000000000000e+00,2.000000000000000000e+00,4.000000000000000000e+00,8.000000000000000000e+00
5.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,2.000000000000000000e+00,1.000000000000000000e+00
9.000000000000000000e+00,6.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00,6.000000000000000000e+00
3.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,9.000000000000000000e+00,2.000000000000000000e+00


In [199]:
csv = np.loadtxt("a.csv", delimiter=',') # delimiter은 구분자임
print(csv)

[[1. 7. 8. 9. 5.]
 [9. 2. 2. 4. 8.]
 [5. 7. 8. 2. 1.]
 [9. 6. 8. 8. 6.]
 [3. 6. 7. 9. 2.]]


In [201]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5')

[[9 4 2 5 5]
 [9 6 5 7 4]
 [5 5 3 5 7]
 [1 7 3 4 6]
 [4 3 3 9 3]]


In [202]:
!cat b.csv

# c1, c2, c3, c4, c5
9.00e+00,4.00e+00,2.00e+00,5.00e+00,5.00e+00
9.00e+00,6.00e+00,5.00e+00,7.00e+00,4.00e+00
5.00e+00,5.00e+00,3.00e+00,5.00e+00,7.00e+00
1.00e+00,7.00e+00,3.00e+00,4.00e+00,6.00e+00
4.00e+00,3.00e+00,3.00e+00,9.00e+00,3.00e+00


In [203]:
csv = np.loadtxt("b.csv", delimiter=",")
print(csv)

[[9. 4. 2. 5. 5.]
 [9. 6. 5. 7. 4.]
 [5. 5. 3. 5. 7.]
 [1. 7. 3. 4. 6.]
 [4. 3. 3. 9. 3.]]
